name: Scrape latest data
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://datafordeler.dk/api/operations/messages/atom -o feed.xml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Feed opdateret: ${timestamp}" || exit 0
        git push
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest]
        width: [1200, 992, 768, 600]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot-${{ matrix.os }}-${{ matrix.width }}.png
        width: ${{ matrix.width }}
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Feed opdateret: ${timestamp}" || exit 0
        git push
